{{- define "base-chart.service" -}}
{{- if .Values.services }}
{{- range .Values.services }}
{{- if .enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ required "Service name is required" .name }}
  namespace: {{ .namespace | default $.Release.Namespace }}
  labels:
    {{- include "base-chart.labels" $ | nindent 4 }}
    {{- with .labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if or $.Values.commonAnnotations .annotations }}
  annotations:
    {{- include "base-chart.annotations" $ | nindent 4 }}
    {{- with .annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  type: {{ .type | default "ClusterIP" }}
  {{- with .clusterIP }}
  clusterIP: {{ . }}
  {{- end }}
  {{- with .clusterIPs }}
  clusterIPs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- with .loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .externalTrafficPolicy }}
  externalTrafficPolicy: {{ . }}
  {{- end }}
  {{- with .internalTrafficPolicy }}
  internalTrafficPolicy: {{ . }}
  {{- end }}
  {{- with .sessionAffinity }}
  sessionAffinity: {{ . }}
  {{- end }}
  {{- with .sessionAffinityConfig }}
  sessionAffinityConfig:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .ipFamilyPolicy }}
  ipFamilyPolicy: {{ . }}
  {{- end }}
  {{- with .ipFamilies }}
  ipFamilies:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  ports:
    {{- range .ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort | default .port }}
      protocol: {{ .protocol | default "TCP" }}
      {{- if and (eq $.type "NodePort") .nodePort }}
      nodePort: {{ .nodePort }}
      {{- end }}
    {{- end }}
  selector:
    {{- if .selectorLabels }}
    {{- toYaml .selectorLabels | nindent 4 }}
    {{- else }}
    {{- include "base-chart.selectorLabels" $ | nindent 4 }}
    {{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
