{{- include "base-chart.deployment" . }}
{{- include "base-chart.service" . }}
{{- include "base-chart.secret" . }}
{{- include "base-chart.configmap" . }}
{{- include "base-chart.serviceaccount" . }}
