#!/usr/bin/env bash
set -euo pipefail

# emit-oci.sh — Generate OCI packaging layer from build preset + manifest
#
# Produces:
#   - oci/sbom.yaml         — artifact manifest (images, charts, binaries)
#   - oci/Dockerfile        — embedded mode (pre-pulled artifacts baked in)
#   - oci/Dockerfile.internet — internet mode (Wolfi base, CLIs from apk)
#   - oci/Taskfile.yaml     — pull/verify/build/push tasks
#
# Usage: ./scripts/emit-oci.sh <app-name|manifest> <release> [output-dir]

: "${1:?Usage: emit-oci.sh <app-name|manifest> <release> [output-dir]}"
RELEASE="${2:?}"
OUTPUT_DIR="${3:-./output}"

BUILD_PRESET="$OUTPUT_DIR/presets/build/${RELEASE}.yaml"
OCI_DIR="$OUTPUT_DIR/oci"

if [ ! -f "$BUILD_PRESET" ]; then
  echo "ERROR: $BUILD_PRESET not found — run generate/emit first"
  exit 1
fi

mkdir -p "$OCI_DIR"

echo "=== Generating OCI packaging layer (release: $RELEASE) ==="

# --- Extract image data from build preset ---
# Build preset has lines like: <key>_image_registry: "value"
#                               <key>_image_repository: "value"
#                               <key>_image_tag: "value"
# Group by prefix to reconstruct full image refs.

IMAGES=$(yq -r 'to_entries | map(select(.key | test("_image_tag$"))) | .[].key | sub("_image_tag$"; "")' "$BUILD_PRESET")

# --- 1. SBOM (artifact manifest) ---
SBOM_FILE="$OCI_DIR/sbom.yaml"

cat > "$SBOM_FILE" << EOF
release: ${RELEASE}
notes: |
  Generated by KLASP.
  Images and charts extracted from build preset.
embed:
  - name: orchestration
    binaries:
      - name: task
        tag: v3.50.0
        url: https://github.com/go-task/task/releases/download/v3.50.0/task_linux_amd64.tar.gz
      - name: gomplate
        tag: v5.1.0
        url: https://github.com/hairyhenderson/gomplate/releases/download/v5.1.0/gomplate_linux-amd64
      - name: sops
        tag: v3.13.1
        url: https://github.com/getsops/sops/releases/download/v3.13.1/sops-v3.13.1.linux.amd64
      - name: yq
        tag: v4.52.1
        url: https://github.com/mikefarah/yq/releases/download/v4.52.1/yq_linux_amd64
      - name: jq
        tag: "1.6"
        url: https://github.com/jqlang/jq/releases/download/jq-1.6/jq-linux64
      - name: kubectl
        tag: v1.26.15
        url: https://dl.k8s.io/release/v1.26.15/bin/linux/amd64/kubectl
      - name: helm
        tag: v4.1.0
        url: https://get.helm.sh/helm-v4.1.0-linux-amd64.tar.gz
      - name: crane
        tag: v0.21.6
        url: https://github.com/google/go-containerregistry/releases/download/v0.21.6/go-containerregistry_Linux_x86_64.tar.gz
      - name: skopeo
        tag: v1.21.0
        url: https://github.com/lework/skopeo-binary/releases/download/v1.21.0/skopeo-linux-amd64
      - name: oras
        tag: v1.3.0
        url: https://github.com/oras-project/oras/releases/download/v1.3.0/oras_1.3.0_linux_amd64.tar.gz
    charts: []
    images:
      - name: helm
        source: cgr.dev/chainguard/helm
        tag: "latest-dev"
      - name: crane
        source: cgr.dev/chainguard/crane
        tag: "latest-dev"
EOF

# Add app images to sbom
for prefix in $IMAGES; do
  registry=$(yq -r ".${prefix}_image_registry // \"\"" "$BUILD_PRESET")
  repo=$(yq -r ".${prefix}_image_repository // \"\"" "$BUILD_PRESET")
  tag=$(yq -r ".${prefix}_image_tag // \"\"" "$BUILD_PRESET")

  # Reconstruct source: registry/repo or just repo if no registry
  if [ -n "$registry" ] && [ "$registry" != "null" ] && [ "$registry" != "\"\"" ]; then
    source="${registry}/${repo}"
  else
    source="$repo"
  fi

  # Derive app name from prefix (replace _ with -)
  app_name=$(echo "$prefix" | tr '_' '-')

  cat >> "$SBOM_FILE" << EOF
  - name: ${app_name}
    charts: []
    binaries: []
    images:
      - name: ${app_name}
        source: ${source}
        tag: "${tag}"
EOF
done

# Add chart entries from build preset
CHART_ENTRIES=$(yq -r 'to_entries | map(select(.key | test("_helm_chart$"))) | .[].key | sub("_helm_chart$"; "")' "$BUILD_PRESET")
for prefix in $CHART_ENTRIES; do
  chart_name=$(yq -r ".${prefix}_helm_chart // \"\"" "$BUILD_PRESET")
  chart_version=$(yq -r ".${prefix}_helm_chart_version // \"\"" "$BUILD_PRESET")
  chart_repo=$(yq -r ".${prefix}_helm_chart_repo // \"\"" "$BUILD_PRESET")
  app_name=$(echo "$prefix" | tr '_' '-')

  # Find the existing app entry and add chart, or create new entry
  # For simplicity, append chart info as a separate entry if needed
  # Check if this app already exists in sbom (has images)
  if echo "$IMAGES" | grep -q "^${prefix}$"; then
    # Already has an entry — patch it (yq in-place)
    yq -i "(.embed[] | select(.name == \"${app_name}\")).charts = [{\"name\": \"${chart_name}\", \"repo\": \"${app_name}\", \"url\": \"${chart_repo}\", \"chart\": \"${chart_name}\", \"version\": \"${chart_version}\"}]" "$SBOM_FILE"
  else
    cat >> "$SBOM_FILE" << EOF
  - name: ${app_name}
    charts:
      - name: ${chart_name}
        repo: ${app_name}
        url: ${chart_repo}
        chart: ${chart_name}
        version: "${chart_version}"
    binaries: []
    images: []
EOF
  fi
done

echo "  Generated: $SBOM_FILE"

# --- 1b. Append tool version tags to build preset ---
# The in-cluster CronJob references $b.sops_tag, $b.gomplate_tag, $b.helm_tag
SOPS_TAG=$(yq -r '.embed[] | select(.binaries != null) | .binaries[] | select(.name == "sops") | .tag' "$SBOM_FILE")
GOMPLATE_TAG=$(yq -r '.embed[] | select(.binaries != null) | .binaries[] | select(.name == "gomplate") | .tag' "$SBOM_FILE")
HELM_TAG=$(yq -r '.embed[] | select(.binaries != null) | .binaries[] | select(.name == "helm") | .tag' "$SBOM_FILE")
CRANE_TAG=$(yq -r '.embed[] | select(.binaries != null) | .binaries[] | select(.name == "crane") | .tag' "$SBOM_FILE")

# Remove any existing tool tags section, then append fresh
sed -i'' -e '/^# --- Orchestration tool versions/,$d' "$BUILD_PRESET"
cat >> "$BUILD_PRESET" << EOF

# --- Orchestration tool versions (used by fetch-binaries init container) ---
sops_tag: "${SOPS_TAG}"
gomplate_tag: "${GOMPLATE_TAG}"
helm_tag: "${HELM_TAG}"
crane_tag: "${CRANE_TAG}"
EOF
echo "  Appended tool tags to: $BUILD_PRESET"

# --- 2. Dockerfile (air-gapped mode) ---
DOCKERFILE="$OCI_DIR/Dockerfile.airgap"

cat > "$DOCKERFILE" << 'EOF'
# KLASP deployer — air-gapped delivery image.
#
# Self-contained offline package: all orchestration CLIs, container images,
# and Helm charts are pre-pulled and embedded. Zero network access at runtime.
# Suitable for disconnected / air-gapped / secure environments.
#
# Build:
#   task -d oci pull        # fetch all artifacts first
#   docker build -f oci/Dockerfile.airgap -t klasp-deployer:<release> .
#
# Run:
#   docker run --rm \
#     -v "$HOME/.kube:/opt/klasp/.kube" \
#     klasp-deployer:<release> apply ENV=<env>

FROM cgr.dev/chainguard/busybox:latest

ENV OPERATOR_HOME=/opt/klasp
WORKDIR ${OPERATOR_HOME}

# Static orchestration binaries (pulled via oci/Taskfile pull-binaries)
COPY oci/artifacts/embed/binaries/task       /usr/local/bin/task
COPY oci/artifacts/embed/binaries/gomplate   /usr/local/bin/gomplate
COPY oci/artifacts/embed/binaries/sops       /usr/local/bin/sops
COPY oci/artifacts/embed/binaries/yq         /usr/local/bin/yq
COPY oci/artifacts/embed/binaries/jq         /usr/local/bin/jq
COPY oci/artifacts/embed/binaries/crane      /usr/local/bin/crane
COPY oci/artifacts/embed/binaries/skopeo     /usr/local/bin/skopeo
COPY oci/artifacts/embed/binaries/kubectl    /usr/local/bin/kubectl
COPY oci/artifacts/embed/binaries/helm       /usr/local/bin/helm
COPY oci/artifacts/embed/binaries/oras       /usr/local/bin/oras

# Embedded OCI artifacts (images + charts)
COPY oci/artifacts/embed/ ./oci/artifacts/embed/

# SBOM
COPY oci/sbom.yaml ./oci/sbom.yaml

# Taskfiles
COPY Taskfile.yaml ./Taskfile.yaml
COPY oci/Taskfile.yaml ./oci/Taskfile.yaml

# Deployer base templates + apply script
COPY base/ ./base/
COPY scripts/apply.sh ./scripts/apply.sh

# Golden configuration + presets + environments
COPY golden-configuration/ ./golden-configuration/
COPY presets/ ./presets/
COPY environments/ ./environments/

# Writable directories for runtime
USER root
RUN mkdir -p ${OPERATOR_HOME}/oci/artifacts/mount \
            ${OPERATOR_HOME}/render \
            ${OPERATOR_HOME}/.kube \
    && chown -R 65534:0 ${OPERATOR_HOME} \
    && chmod -R g=u ${OPERATOR_HOME}

ENV HOME=${OPERATOR_HOME} \
    KUBECONFIG=${OPERATOR_HOME}/.kube/config \
    OPERATOR_MODE=airgap

USER 65534

ENTRYPOINT ["task"]
CMD ["--list"]
EOF

echo "  Generated: $DOCKERFILE"

# --- 3. Dockerfile (runtime-pull mode) ---
DOCKERFILE_INTERNET="$OCI_DIR/Dockerfile.online"

cat > "$DOCKERFILE_INTERNET" << 'EOF'
# KLASP deployer — online delivery image.
#
# Pulls deployment OCI artifacts (images, charts) from registries at runtime.
# Lightweight image with CLIs pre-installed from Wolfi packages.
# Requires network access to container registries during deployment.
# OpenShift restricted-SCC compatible (arbitrary UID in group 0).
#
# Build:
#   docker build -f oci/Dockerfile.online -t klasp-deployer:<release> .
#
# Run:
#   docker run --rm -e ENV=<env> \
#     -v "$HOME/.kube:/opt/klasp/.kube:ro" \
#     klasp-deployer:<release> apply

FROM cgr.dev/chainguard/wolfi-base:latest

RUN apk add --no-cache \
        bash \
        coreutils \
        gzip \
        curl \
        ca-certificates-bundle \
        git \
        jq \
        task \
        gomplate \
        sops \
        age \
        yq \
        kubectl \
        helm \
        crane \
        oras \
        skopeo \
        aws-cli-v2

ENV OPERATOR_HOME=/opt/klasp
WORKDIR ${OPERATOR_HOME}

# Taskfiles
COPY Taskfile.yaml ./Taskfile.yaml
COPY oci/Taskfile.yaml ./oci/Taskfile.yaml
COPY oci/sbom.yaml ./oci/sbom.yaml

# Deployer base templates + apply script
COPY base/ ./base/
COPY scripts/apply.sh ./scripts/apply.sh

# Golden configuration + presets + environments
COPY golden-configuration/ ./golden-configuration/
COPY presets/ ./presets/
COPY environments/ ./environments/

# OpenShift compatible: group 0 writable
RUN mkdir -p ${OPERATOR_HOME}/oci/artifacts \
            ${OPERATOR_HOME}/render \
            ${OPERATOR_HOME}/.kube \
    && chgrp -R 0 ${OPERATOR_HOME} \
    && chmod -R g=u ${OPERATOR_HOME}

ENV HOME=${OPERATOR_HOME} \
    KUBECONFIG=${OPERATOR_HOME}/.kube/config \
    OPERATOR_MODE=online

USER 1001

ENTRYPOINT ["task"]
CMD ["--list"]
EOF

echo "  Generated: $DOCKERFILE_INTERNET"

# --- 4. OCI Taskfile ---
OCI_TASKFILE="$OCI_DIR/Taskfile.yaml"

cat > "$OCI_TASKFILE" << 'TASKEOF'
version: '3'

vars:
  ARTIFACTS_DIR: ./artifacts
  MANIFEST: ./sbom.yaml

tasks:
  default:
    silent: true
    cmd: task --list

  _validate-manifest:
    internal: true
    silent: true
    preconditions:
      - sh: test -f "{{.MANIFEST}}"
        msg: "manifest file {{.MANIFEST}} not found"
      - sh: command -v yq >/dev/null
        msg: "yq is required"

  pull:
    desc: pull all artifacts (binaries + charts + images)
    silent: true
    deps:
      - pull-binaries
      - pull-charts
      - pull-images

  pull-binaries:
    desc: pull orchestration binaries from URLs in sbom.yaml
    silent: true
    deps: [_validate-manifest]
    preconditions:
      - sh: command -v curl >/dev/null
        msg: "curl is required"
    cmds:
      - |
        entries=$(yq -r '
        .embed[]
        | select(.binaries != null and (.binaries | length) > 0)
        | .binaries[]
        | "\(.name) \(.url)"
        ' {{.MANIFEST}} 2>/dev/null | grep -v '^\s*$' | grep '[a-zA-Z0-9]' || true)

        if [ -z "$entries" ]; then
          echo "  No binaries to pull"
          exit 0
        fi

        echo "=== Pulling binaries ==="
        mkdir -p {{.ARTIFACTS_DIR}}/embed/binaries
        echo "$entries" | \
        while read -r name url; do
          dest="{{.ARTIFACTS_DIR}}/embed/binaries/$name"
          if [ -f "$dest" ]; then echo "  SKIP: $name (exists)"; continue; fi
          echo "  $name -> $dest"
          if echo "$url" | grep -q '\.tar\.gz$'; then
            tmpdir=$(mktemp -d)
            curl -fsSL "$url" | tar -xzf - -C "$tmpdir"
            found=$(find "$tmpdir" -type f -name "$name" | head -1)
            if [ -z "$found" ]; then
              found=$(find "$tmpdir" -type f -executable | head -1)
            fi
            if [ -z "$found" ]; then
              echo "    ERROR: no binary found in archive for $name"
              rm -rf "$tmpdir"
              continue
            fi
            mv "$found" "$dest"
            rm -rf "$tmpdir"
          else
            curl -fsSL "$url" -o "$dest"
          fi
          chmod +x "$dest"
        done

  pull-charts:
    desc: pull helm charts defined in sbom.yaml
    silent: true
    deps: [_validate-manifest]
    preconditions:
      - sh: command -v helm >/dev/null
        msg: "helm is required"
    cmds:
      - |
        charts=$(yq -r '
        .embed[]
        | select(.charts != null and (.charts | length) > 0)
        | .name as $app
        | .charts[]
        | "\($app) \(.repo) \(.url) \(.chart) \(.version)"
        ' {{.MANIFEST}} 2>/dev/null | grep -v '^\s*$' | grep '[a-zA-Z0-9]' || true)

        if [ -z "$charts" ]; then
          echo "  No charts to pull"
          exit 0
        fi

        echo "=== Setting up helm repositories ==="
        echo "$charts" | awk '{print $2, $3}' | sort -u | \
        while read -r repo url; do
          if echo "$url" | grep -q '^oci://'; then
            echo "  OCI registry: $url"
          else
            echo "  Adding helm repo: $repo -> $url"
            helm repo add "$repo" "$url" 2>/dev/null || true
          fi
        done
        helm repo update 2>/dev/null || true

        echo "=== Pulling charts ==="
        echo "$charts" | \
        while read -r app repo url chart version; do
          chart_dir="{{.ARTIFACTS_DIR}}/embed/charts/$app"
          mkdir -p "$chart_dir"
          if echo "$url" | grep -q '^oci://'; then
            echo "  ${url}/${chart}:${version} -> $chart_dir/"
            helm pull "${url}/${chart}" --version "$version" --destination "$chart_dir"
          else
            echo "  $repo/$chart:$version -> $chart_dir/"
            helm pull "$repo/$chart" --version "$version" --destination "$chart_dir"
          fi
        done

  pull-images:
    desc: pull container images as OCI layout (linux/amd64)
    silent: true
    deps: [_validate-manifest]
    preconditions:
      - sh: command -v skopeo >/dev/null
        msg: "skopeo is required"
    cmds:
      - |
        entries=$(yq -r '
        .embed[]
        | select(.images != null and (.images | length) > 0)
        | .name as $app
        | .images[]
        | "\($app) \(.name) \(.source) \(.tag)"
        ' {{.MANIFEST}} 2>/dev/null | grep -v '^\s*$' | grep '[a-zA-Z0-9]' || true)

        if [ -z "$entries" ]; then
          echo "  No images to pull"
          exit 0
        fi

        echo "=== Pulling images (linux/amd64) ==="
        echo "$entries" | \
        while read -r app name source tag; do
          image_dir="{{.ARTIFACTS_DIR}}/embed/images/$app/$name/$tag"
          if [ -f "$image_dir/index.json" ]; then echo "  SKIP: $app/$name:$tag (exists)"; continue; fi
          mkdir -p "$image_dir"
          echo "  $source:$tag -> $image_dir/"
          if ! skopeo --insecure-policy copy \
            --override-arch amd64 --override-os linux \
            --remove-signatures \
            "docker://$source:$tag" "oci:$image_dir"; then
            echo "  FAIL: $source:$tag"
            rm -rf "$image_dir"
          fi
        done

  verify:
    desc: verify all artifacts exist locally
    silent: true
    deps: [_validate-manifest]
    cmds:
      - |
        ERRORS=0
        echo "=== Verifying artifacts ==="

        echo "  Binaries:"
        yq -r '.embed[] | select(.binaries != null) | .binaries[] | .name' {{.MANIFEST}} 2>/dev/null | \
        while read -r name; do
          if [ -f "{{.ARTIFACTS_DIR}}/embed/binaries/$name" ]; then
            echo "    [OK] $name"
          else
            echo "    [MISSING] $name"
          fi
        done

        echo "  Charts:"
        yq -r '
        .embed[]
        | select(.charts != null and (.charts | length) > 0)
        | .name as $app
        | .charts[]
        | "\($app) \(.chart) \(.version)"
        ' {{.MANIFEST}} 2>/dev/null | grep -v '^\s*$' | grep '[a-zA-Z0-9]' | \
        while read -r app chart version; do
          chart_file="{{.ARTIFACTS_DIR}}/embed/charts/$app/${chart}-${version}.tgz"
          if [ -f "$chart_file" ]; then
            echo "    [OK] $app/$chart:$version"
          else
            echo "    [MISSING] $app/$chart:$version"
          fi
        done || true

        echo "  Images:"
        yq -r '
        .embed[]
        | select(.images != null and (.images | length) > 0)
        | .name as $app
        | .images[]
        | "\($app) \(.name) \(.tag)"
        ' {{.MANIFEST}} 2>/dev/null | grep -v '^\s*$' | grep '[a-zA-Z0-9]' | \
        while read -r app name tag; do
          image_dir="{{.ARTIFACTS_DIR}}/embed/images/$app/$name/$tag"
          if [ -d "$image_dir" ] && [ -f "$image_dir/index.json" ]; then
            echo "    [OK] $app/$name:$tag"
          else
            echo "    [MISSING] $app/$name:$tag"
          fi
        done

  build:
    desc: "build klasp-deployer Docker image (MODE=airgap|online)"
    silent: true
    vars:
      MODE: '{{.MODE | default "airgap"}}'
      TAG: '{{.TAG | default "latest"}}'
      IMAGE: '{{.IMAGE | default "klasp-deployer"}}'
    cmds:
      - |
        if [ "{{.MODE}}" = "online" ]; then
          echo "=== Building: {{.IMAGE}}:{{.TAG}} (online — pulls artifacts at runtime) ==="
          docker build -f oci/Dockerfile.online -t "{{.IMAGE}}:{{.TAG}}" ..
        else
          echo "=== Building: {{.IMAGE}}:{{.TAG}} (airgap — self-contained offline) ==="
          echo "  Ensure 'task -d oci pull' has been run first."
          docker build -f oci/Dockerfile.airgap -t "{{.IMAGE}}:{{.TAG}}" ..
        fi

  push:
    desc: "push klasp-deployer image to registry"
    silent: true
    vars:
      TAG: '{{.TAG | default "latest"}}'
      IMAGE: '{{.IMAGE | default "klasp-deployer"}}'
      REGISTRY: '{{.REGISTRY}}'
    preconditions:
      - sh: '[ -n "{{.REGISTRY}}" ]'
        msg: "REGISTRY is required (e.g., ghcr.io/org/repo)"
    cmds:
      - |
        FULL_IMAGE="{{.REGISTRY}}/{{.IMAGE}}:{{.TAG}}"
        echo "=== Pushing: $FULL_IMAGE ==="
        docker tag "{{.IMAGE}}:{{.TAG}}" "$FULL_IMAGE"
        docker push "$FULL_IMAGE"
        echo "  Done: $FULL_IMAGE"

  clean:
    desc: remove all pulled artifacts
    silent: true
    cmds:
      - rm -rf {{.ARTIFACTS_DIR}}
      - echo "Cleaned {{.ARTIFACTS_DIR}}"
TASKEOF

echo "  Generated: $OCI_TASKFILE"

echo ""
echo "=== OCI packaging layer complete ==="
echo "  Output directory: $OCI_DIR/"
echo "  Files:"
echo "    - oci/sbom.yaml"
echo "    - oci/Dockerfile.airgap        (self-contained offline package)"
echo "    - oci/Dockerfile.online       (pulls OCI artifacts at runtime)"
echo "    - oci/Taskfile.yaml           (pull/verify/build/push)"
